services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama        
    ports:
      - "11434:11434"
    entrypoint: ["/bin/bash", "-c", "ollama pull llama3.1:8b-instruct-q4_K_M && exec ollama serve"]
  app:
    build: .
    container_name: llama_gui
    depends_on:
      - ollama
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
volumes:
  ollama_data: